feat: Introduce buffer timeout
cursorinsight/ci-trap-web pull request #37
Opened 2024-03-08 16:14 UTC by gbence

`bufferTimeout` enables Trap to guarantee that events don't wait longer in the client buffer than it is expected.

2024-03-08 16:42 UTC, denessapi commented on src/trap.js
> +  // `bufferSizeLimit` setter proxy
bufferTimeout

2024-03-08 16:45 UTC, denessapi requested changes
Just minor things

2024-03-08 16:45 UTC, denessapi commented on test/trap.buffer-timeout.test.js
> +  test('sends chunks automatically on buffer fill', () => {
on buffer timeout

2024-03-08 16:45 UTC, denessapi commented on src/trap.js
> +  // `bufferSizeLimit` setter proxy
bufferTimeout

2024-03-09 21:47 UTC, gbence commented on src/trap.js
> +  // `bufferSizeLimit` setter proxy
Done

2024-03-09 21:47 UTC, gbence commented on test/trap.buffer-timeout.test.js
> +  test('sends chunks automatically on buffer fill', () => {
Done

2024-03-10 09:28 UTC, merged