Rework examples and upgrade dependencies
cursorinsight/ci-trap-web pull request #39
Opened 2024-03-26 16:32 UTC by gbence

In order to resolve all security issues in the project unnecessary/not maintained examples are removed -- e.g. React and Angular integrations which add the most.

2024-03-26 17:08 UTC, denessapi requested changes

2024-03-26 17:08 UTC, denessapi commented on .eslintrc.js
I think the react warning comes from the eslint-config-airbnb, as that package contains the react eslint plugins as well.
Switching to the eslint-config-airbnb-base package would also solve this issue, without the hack (and modifying .eslintrc.js to extend airbnb-base instead of airbnb).

2024-03-27 00:44 UTC, gbence commented on .eslintrc.js
Thanks, made the necessary changes.

2024-03-27 06:33 UTC, denessapi approved these changes

2024-03-27 09:46 UTC, merged